//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public string Alias { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<int> IsEnabled { get; set; }
        public Nullable<int> IsTrusted { get; set; }
        public string BitcoinWallet { get; set; }
        public string EtherWallet { get; set; }
        public string LiteCoinWallet { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ACType { get; set; }
        public string Gender { get; set; }
        public string Seeking { get; set; }
        public string AboutMe { get; set; }
        public string IAmSeeking { get; set; }
        public string LookingFor { get; set; }
        public string Height { get; set; }
        public string BodyType { get; set; }
        public string Ethnicity { get; set; }
        public string HairColor { get; set; }
        public string Occupation { get; set; }
        public string Education { get; set; }
        public string RelationShip { get; set; }
        public string Children { get; set; }
        public string Smoking { get; set; }
        public string Drinking { get; set; }
        public string Language { get; set; }
        public string Heading { get; set; }
        public string LifeStyle { get; set; }
        public string NetWorth { get; set; }
        public string AnnualIncome { get; set; }
        public Nullable<int> IsFilled { get; set; }
        public System.Data.Entity.Spatial.DbGeography Place { get; set; }
        public string PlaceName { get; set; }
    }
}
